---

- name: Validate Configurations
  include_tasks: validate.yml

- name: Configure Networking
  include_tasks: configure_networking.yml

- name: Configure Storage
  include_tasks: configure_storage.yml

- name: Configure TLS
  include_tasks: configure_tls.yml

- name: Configure Reporting
  include_tasks: configure_reporting.yml

- name: Store MeteringConfig spec into values file
  copy: content="{{ meteringconfig_spec }}" dest=/tmp/metering-values.yaml

# TODO: reconcile Hive/HDFS when the default ReportDataSources are used
# Note: hadoop-config is used by Presto
- include_tasks: "{{ item }}"
  loop:
    - reconcile_metering.yml
    - reconcile_monitoring.yml
    - reconcile_hdfs.yml
    # - reconcile_hive.yml
    - reconcile_presto.yml
    - reconcile_reporting_operator.yml
    - reconcile_reporting.yml
